// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tomuyymasqoisegoxsqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvbXV5eW1hc3FvaXNlZ294c3FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MDE2OTQsImV4cCI6MjA3NjE3NzY5NH0.O6e5Z2sgAJNU7IcVImcVZhMuDhYEsmeSRL5MsJlp2UM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});